@startuml
用户 -> 系统: 1:                    获取源程序
系统 --> 用户:2:                  显示源程序
用户 -> 系统: 3:                   获取关系矩阵
系统 <-- 用户: 4:  显示弱变异分析得到的二进制关系矩阵
用户--> 系统: 5:            设置线程数，种群数等参数
系统--> 用户: 6:            显示简约后测试用例信息

@enduml